_BASE_: "../base_att_image_caption.yaml"

DATALOADER:
  FEATS_FOLDER: ''
  GV_FEAT_FILE: 'datasets/mscoco_dataset/features/global_feat/resnet101_pool5.pkl'
  ATTRIBUTE_FILE: 'datasets/mscoco_dataset/features/mil/resnet101_mil.pkl'

######################################### MODEL #########################################
MODEL:
  DECODER: 'AttributeDecoder'
  DECODER_DIM: 1024

  VISUAL_EMBED:
    NAME: 'VisualIdentityEmbedding'

  LSTMA:
    ATTRIBUTE_DIM: 1000
    DROPOUT: 0.

####################################### losses ####################################### 
LOSSES:
  NAMES: ['CrossEntropy']
